const puppeteer = require('puppeteer');
const path = require('path');

async function performScreenshot() {

	const browser = await puppeteer.launch();
	  const page = await browser.newPage();
	  await page.setViewport({
		width: 1280,
		height: 720
	  });
	  await page.goto('https://www.google.com');
	  await page.type("#lst-ib", "OK Google");
	  const savePath = path.join(__dirname, 'google.png')
	  await page.screenshot({path: savePath});

	  await browser.close();

	return "Success"
}

/**
 * This method demonstrate the export pdf feature of puppeteer.
 * It opens a page and exports the page to a pdf.
 */
async function exportPDF() {
	// Opens chromium in a headless state
	const browser = await puppeteer.launch();

	const page = await browser.newPage();
	await page.setViewport({
		width: 1280,
		height: 720
	});
	await page.goto('https://github.com/jigar1101/puppeteer-demos');
	await page.pdf({path: 'sample_pdf.pdf', format: 'A4'});
	
	await browser.close();
	return "A pdf was successfully generated by the name of <b>sample_pdf<b> at the root of this directory."
}


module.exports = {
	performScreenshot,
	exportPDF
 }